version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    container_name: filin-postgres13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    container_name: filin-web
    image: ${DOCKER_USERNAME}/${DOCKER_PROJECT}
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  bot:
    container_name: filin-bot
    image: ${DOCKER_USERNAME}/${DOCKER_BOT}
    restart: always
    env_file:
      - ./.env
    depends_on:
      - web

  nginx:
    container_name: filin-nginx
    image: nginx:1.21.3-alpine
    ports:
      - 83:83
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - web

volumes:
  static:
  media:
  postgres:
