# Generated by Django 4.1 on 2022-09-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Широта")),
                ("longitude", models.FloatField(verbose_name="Долгота")),
            ],
            options={
                "verbose_name": "Местоположение",
                "verbose_name_plural": "Местоположение",
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("data", models.FloatField(verbose_name="Показатель")),
            ],
            options={
                "verbose_name": "Статистика",
                "verbose_name_plural": "Статистика",
            },
        ),
        migrations.CreateModel(
            name="StatType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=32, unique=True, verbose_name="Уникальное название"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=512, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("float", "Число с плавающей точкой"),
                            ("int", "Целое число"),
                        ],
                        default="float",
                        max_length=10,
                        verbose_name="Тип данных",
                    ),
                ),
                ("min_value", models.FloatField(verbose_name="Минимальное значение")),
                ("max_value", models.FloatField(verbose_name="Максимальное значение")),
            ],
            options={
                "verbose_name": "Тип данных",
                "verbose_name_plural": "Типы данных",
            },
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("code", models.IntegerField(verbose_name="Вид осадков")),
                ("temp", models.FloatField(verbose_name="Температура по Цельсию")),
                (
                    "pressure",
                    models.PositiveIntegerField(verbose_name="Атмосферное давление"),
                ),
                (
                    "humidity",
                    models.PositiveBigIntegerField(verbose_name="Влажность воздуха %"),
                ),
            ],
            options={
                "verbose_name": "Погода",
                "verbose_name_plural": "Погода",
            },
        ),
    ]
