# Generated by Django 4.1 on 2022-09-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stat",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="users.patient",
                verbose_name="Пациент",
            ),
        ),
        migrations.AddField(
            model_name="stat",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="stats.stattype",
                verbose_name="Тип",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.patient",
                verbose_name="locations",
            ),
        ),
    ]
