# Generated by Django 4.1 on 2022-08-31 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stats",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.patient",
                verbose_name="stats",
            ),
        ),
        migrations.AddField(
            model_name="pressure",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.patient",
                verbose_name="pressures",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="users.patient",
                verbose_name="locations",
            ),
        ),
    ]
