# Generated by Django 4.1 on 2022-10-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stattype',
            name='important',
            field=models.BooleanField(blank=True, default=False, verbose_name='Важное значение'),
        ),
    ]
