# Generated by Django 4.1 on 2022-10-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='age',
            new_name='date_of_birth',
        ),
    ]
