# Generated by Django 4.1 on 2022-10-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_age_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='telegram',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='telegram id'),
        ),
    ]
