name: filin_mate workflow

on: [push]

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: usolev
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Web to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          file: filin_mate/Dockerfile
          context: filin_mate/
          push: true
          tags: usolev/filin_mate:latest
      - name: Push Bot to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          file: telegram_bot/Dockerfile
          context: telegram_bot/
          push: true
          tags: usolev/filin_mate_bot:latest
